### ISSUE TITLE
How do i use Vtfcmd

### ISSUE THREAD

**Issue by Sharikfi** [Sky-rym/VTFEdit-Reloaded#17]
i used a bat file with args:

`VTFEditR.exe -folder "D:\Source2\rp_bangclaw2\materials\brick\*.vtf" -output "D:\Source2\rp_bangclaw2\export\brick" -exportformat "png"`
and opened cmd, vtfedit, and nothing happened

**Comment by JayBoom** [comment]
Yeah the install is slightly confusing, hopefully the owner can make an .exe that automates a lot of this as installing it seems hard

**Comment by byteframe** [comment]
Also, can the developer please include a vtfcmd binary in the release zip?
