### ISSUE TITLE
New Icon

### ISSUE THREAD

**Issue by LillyWho** [Sky-rym/VTFEdit-Reloaded#23]
It might be a good idea to ask around for an artist who could create a new icon for the exe, since the original vtfedit one is... Well, _weird._
Something actually to do with vtf files would be nice, rather than, what, Jessica Rabbit?

**Comment by Sky-rym** [comment]
maybe, just to differentiate reloaded a bit more than just blue vtfedit but what we have now is fine
if someone makes one and i like it sure but for now im just keeping it as is
