### ISSUE TITLE
VTF -> TGA removes alpha!

### ISSUE THREAD

**Issue by NvC-DmN-CH** [Sky-rym/VTFEdit-Reloaded#26]
VTFCmd also does this, the issue must be from VTFLib

**Comment by DBONKA** [comment]
Tested converting VTF with Alpha to TGA using AutoVTF, TGA still had the Alpha channel after the conversion.
But converting PSD with Alpha into VTF loses the alpha channel (opened a separate issue for that)

**Comment by NvC-DmN-CH** [comment]
nevermind, I imported as RGB888 instead of BGRA8888
